import Foundation
import Testing

@testable import ReparaCore

/// Phase 1 of the handoff, and the one that gates everything else.
///
/// A projection that is subtly wrong does not fail loudly — it files a
/// plausible-looking report against the building next door, and a council
/// worker is dispatched to the wrong address. These tests are the only thing
/// standing between a refactor and that outcome.
@Suite("Projection")
struct ProjectionTests {

    // MARK: The reference pair

    @Test("reproduces the portal reference point")
    func referencePoint() throws {
        try Projection.verify()

        let got = Projection.forward(Projection.reference.wgs84)
        let drift = got.distance(to: Projection.reference.ptTm06)
        #expect(
            drift < 0.001,
            "drift \(drift) m should be sub-millimetre, not merely inside the 1 m tolerance"
        )
    }

    @Test("round-trips")
    func roundTrip() {
        let there = Projection.reference.ptTm06
        let back = Projection.forward(Projection.inverse(there))
        #expect(back.distance(to: there) < 0.001)
    }

    // MARK: The negative test

    /// The portal's own forward call passes `transformation=108153`, landing
    /// ~114 m from the truth — the bug behind its misplaced map picker. This
    /// test exists so nobody "fixes" our projection by matching the portal.
    @Test("does NOT reproduce the portal map-picker offset")
    func doesNotReproducePortalBug() {
        let ours = Projection.forward(Projection.reference.wgs84)
        let theirs = Projection.portalForwardBug.ptTm06

        let gap = ours.distance(to: theirs)
        let expected = Projection.portalForwardBug.magnitudeMetres
        #expect(
            abs(gap - expected) < 1,
            "expected ~\(expected) m from the portal's shifted output, got \(gap)"
        )

        // The offset is a constant datum shift, not a scaling or a rotation:
        // the same dx/dy was measured kilometres away. If this drifts, the
        // finding itself is wrong and the comment above needs revisiting.
        #expect(abs(theirs.x - ours.x - Projection.portalForwardBug.shift.dx) < 0.5)
        #expect(abs(theirs.y - ours.y - Projection.portalForwardBug.shift.dy) < 0.5)
    }

    // MARK: Cross-check against proj4

    /// The reference pair alone is a weak test: it sits almost on the latitude
    /// of origin, so a wrong Krüger coefficient can hide there and only show up
    /// as metres of error elsewhere in the city. These rows were generated by
    /// the TypeScript client via proj4 and cover the whole municipality.
    @Test("agrees with proj4 across Lisbon")
    func agreesWithProj4() throws {
        let fixture = try ProjectionFixture.load()
        #expect(fixture.points.count >= 10, "fixture should cover the city, not one point")

        var worstForward = 0.0
        var worstInverse = 0.0

        for point in fixture.points {
            let expected = PtTm06(x: point.x, y: point.y)
            let got = Projection.forward(LatLng(lat: point.lat, lng: point.lng))
            let drift = got.distance(to: expected)
            worstForward = max(worstForward, drift)
            #expect(drift < 0.001, "\(point.name): forward drifted \(drift) m from proj4")

            let back = Projection.inverse(expected)
            // Degrees to metres, near enough for an assertion at this latitude.
            let backDrift = hypot(
                (back.lat - point.backLat) * 111_320,
                (back.lng - point.backLng) * 111_320 * cos(point.lat * .pi / 180)
            )
            worstInverse = max(worstInverse, backDrift)
            #expect(backDrift < 0.001, "\(point.name): inverse drifted \(backDrift) m from proj4")
        }

        print(
            "proj4 cross-check: worst forward \(worstForward) m, worst inverse \(worstInverse) m "
                + "across \(fixture.points.count) points"
        )
    }

    @Test("forward and inverse are mutually consistent across the city")
    func selfConsistent() throws {
        for lat in stride(from: 38.68, through: 38.82, by: 0.02) {
            for lng in stride(from: -9.26, through: -9.06, by: 0.02) {
                let original = LatLng(lat: lat, lng: lng)
                let there = Projection.forward(original)
                let back = Projection.inverse(there)
                let again = Projection.forward(back)
                #expect(again.distance(to: there) < 0.0001)
            }
        }
    }

    // MARK: Bounds

    @Test("Lisbon bounds accept the city and reject elsewhere")
    func bounds() {
        #expect(Projection.isInLisbon(Projection.reference.wgs84))
        #expect(Projection.isInLisbon(LatLng(lat: 38.7679, lng: -9.0994)))  // Parque das Nações
        #expect(!Projection.isInLisbon(LatLng(lat: 41.1579, lng: -8.6291)))  // Porto
        #expect(!Projection.isInLisbon(LatLng(lat: 38.5244, lng: -8.8882)))  // Setúbal
        #expect(!Projection.isInLisbon(LatLng(lat: 0, lng: 0)))
    }
}

// MARK: - Fixture

struct ProjectionFixture: Decodable {
    struct Point: Decodable {
        let name: String
        let lat: Double
        let lng: Double
        let x: Double
        let y: Double
        let backLat: Double
        let backLng: Double
    }

    let note: String
    let source: String
    let points: [Point]

    static func load() throws -> ProjectionFixture {
        let url = try #require(
            Bundle.module.url(forResource: "projection", withExtension: "json"),
            "projection.json is missing from the test bundle"
        )
        return try JSONDecoder().decode(ProjectionFixture.self, from: Data(contentsOf: url))
    }
}
