import Foundation
import Testing

@testable import ReparaCore

/// The portal scopes `nearBy` to the one `ocoTipo` asked for — 89 of 89 entries
/// in the captured session were the type requested, and the same coordinate
/// returns nothing at all for a type nobody has filed there. So a report can
/// only ever be checked against its own category unless the app goes and asks
/// under another one.
///
/// This is the map that decides which other ones are worth asking under, and
/// what to say about the answer.
@Suite("Related types")
struct RelatedTypeTests {

    private let taxonomy = Taxonomy.bundled

    // MARK: The case this exists for

    /// One resident books a bulky-waste collection and puts the mattress out.
    /// Somebody else walks past, sees an abandoned mattress, and files
    /// fly-tipping. Two type ids, one mattress, and the second report sends a
    /// worker to a job already on somebody's list.
    @Test("fly-tipping looks under the bulky-waste collection requests")
    func mattress() throws {
        let flyTipping = try #require(taxonomy.type(id: 97))
        let related = taxonomy.related(to: flyTipping)

        let monstros = try #require(related.first { $0.id == 256 })
        #expect(monstros.relation == .collectedByRequest)
        #expect(monstros.type.descricao.contains("Monstros"))

        // And the other two collection requests a pile on a pavement could be:
        // construction debris and garden waste.
        #expect(related.contains { $0.id == 257 && $0.relation == .collectedByRequest })
        #expect(related.contains { $0.id == 258 && $0.relation == .collectedByRequest })
    }

    /// The user's own words: someone reports the mattress "under abandoned bin
    /// bags or other litter". That is a different id again, and it must reach
    /// the same collection requests.
    @Test("abandoned litter reaches the collection requests too")
    func litter() throws {
        let related = taxonomy.related(to: .litter, matching: .collectedByRequest)
        #expect(related.contains { $0.id == 256 })
    }

    /// Filing a collection request is not a wasted dispatch — it is how the
    /// council is *supposed* to be told. So the reverse direction must not be
    /// `.collectedByRequest`, or `AppModel` would spend requests unasked on the
    /// one case where nothing is being wasted.
    @Test("the reverse direction is not a collection warning")
    func reverseIsNotAWarning() throws {
        let monstros = try #require(taxonomy.type(id: 256))
        let related = taxonomy.related(to: monstros)

        let flyTipping = try #require(related.first { $0.id == 97 })
        #expect(flyTipping.relation == .sameProblem)
        #expect(taxonomy.related(to: monstros, matching: .collectedByRequest).isEmpty)
    }

    // MARK: The derived half

    /// Five descriptions are worded identically in two areas. `Taxonomy.resolve`
    /// already has to disambiguate them with a `--<area>` slug; the same fact
    /// makes them confusable when *filing*, and it costs no curation to say so.
    @Test("identical wording across two areas relates without being curated")
    func collisionsAreDerived() throws {
        // Desporto and Educação both call it "Manutenção e/ou reparação", and
        // neither is in a curated cluster — this pair exists only because the
        // wording collides.
        let desporto = try #require(taxonomy.type(id: 111))
        let related = taxonomy.related(to: desporto)

        #expect(related.count == 1)
        #expect(related[0].id == 521)
        #expect(related[0].relation == .sameProblem)
        #expect(
            !CuratedClusters.all.contains { $0.problems.contains(111) || $0.requests.contains(111) },
            "and it is derived, not hand-written — that is the point of the test")
    }

    @Test("every colliding description finds its twin")
    func everyCollision() throws {
        var wording: [String: [Int]] = [:]
        for type in taxonomy.types { wording[slugify(type.descricao), default: []].append(type.id) }
        let colliding = wording.values.filter { $0.count > 1 }

        #expect(colliding.count == 5, "the five the taxonomy notes are duplicated across areas")

        for ids in colliding {
            for id in ids {
                let type = try #require(taxonomy.type(id: id))
                let related = taxonomy.related(to: type).map(\.id)
                for twin in ids where twin != id {
                    #expect(related.contains(twin), "\(id) should find its twin \(twin)")
                }
            }
        }
    }

    // MARK: Integrity of the curated table

    /// A curated id that no longer exists is a warning that silently stops
    /// appearing. `taxonomy.json` is regenerated by hand from the TypeScript
    /// client, so this is the check that the two have not drifted apart.
    @Test("every curated id is a real type in the bundled taxonomy")
    func noDanglingIds() {
        for cluster in CuratedClusters.all {
            for id in cluster.problems + cluster.requests {
                #expect(taxonomy.type(id: id) != nil, "curated id \(id) is not in the taxonomy")
            }
        }
    }

    /// Every id in `requests` must actually be a request — the app fetches these
    /// on its own initiative and tells somebody their problem may already be
    /// booked in. A complaint type mislabelled here produces a confident, wrong
    /// warning. The portal words them all the same way, which makes this
    /// checkable rather than a matter of opinion.
    @Test("everything labelled a request is worded as one")
    func requestsAreRequests() throws {
        for cluster in CuratedClusters.all {
            for id in cluster.requests {
                let type = try #require(taxonomy.type(id: id))
                let wording = type.descricao.lowercased()
                #expect(
                    ["pedido", "recolha", "remoção", "lavagem"].contains(where: wording.contains),
                    "\(id) \"\(type.descricao)\" is labelled a request but is not worded as one")
            }
        }
    }

    @Test("no type is related to itself")
    func noSelfReference() {
        for type in taxonomy.types {
            #expect(!taxonomy.related(to: type).contains { $0.id == type.id })
        }
    }

    @Test("a type nobody confuses has no related types")
    func unrelatedTypesStayUnrelated() throws {
        // Graffiti is graffiti. Nothing else in 127 types describes it.
        let graffiti = try #require(taxonomy.type(id: 98))
        #expect(taxonomy.related(to: graffiti).isEmpty)
    }

    // MARK: The request budget

    /// Each related type is one more `getGeoAttributes` call at a municipal
    /// server. The cap is the whole reason this is a curated list rather than
    /// "everything in the area".
    @Test("no type can cost more than the cap in extra requests")
    func capIsHonoured() {
        #expect(Taxonomy.maxRelatedLookups == 3)
        for type in taxonomy.types {
            #expect(taxonomy.related(to: type).count <= Taxonomy.maxRelatedLookups)
        }
    }

    /// Under a cap, order decides what gets dropped. Collection requests are
    /// what the app spends requests on unasked, so they must never be the ones
    /// squeezed out by a merely-similar complaint type.
    @Test("collection requests are never dropped in favour of similar complaints")
    func requestsRankFirst() throws {
        for type in taxonomy.types {
            let related = taxonomy.related(to: type)
            let lastRequest = related.lastIndex { $0.relation == .collectedByRequest }
            let firstProblem = related.firstIndex { $0.relation == .sameProblem }
            if let lastRequest, let firstProblem {
                #expect(lastRequest < firstProblem, "\(type.id) ordered a complaint above a request")
            }
        }
    }

    @Test("filtering by relation returns only that relation")
    func filtering() throws {
        let flyTipping = try #require(taxonomy.type(id: 97))
        let requests = taxonomy.related(to: flyTipping, matching: .collectedByRequest)

        #expect(!requests.isEmpty)
        #expect(requests.allSatisfy { $0.relation == .collectedByRequest })
    }

    /// The cap applies to what is asked for, not to what is thrown away first.
    /// Filtering to collection requests must not return two because a
    /// `.sameProblem` entry used up a slot.
    @Test("filtering does not lose entries to the cap")
    func filteringIsNotStarvedByTheCap() throws {
        let flyTipping = try #require(taxonomy.type(id: 97))
        #expect(taxonomy.related(to: flyTipping, matching: .collectedByRequest).count == 3)
    }
}
